<?php

/**
 * @file
 * A module that allows exporting of content in JSON format.
 * 
 */

/**
 * Implements hook_help().
 */
function contentexport_help($path, $args) {
  if ($path === 'admin/help#content_export') {
    return '<p>' . t('A module that allows exporting of content in JSON format.') . '</p>';
  }
}

/**
 * Implements hook_menu().
 */
function contentexport_menu() {
  $items['export/select'] = array(
    'title' => 'Export content',
    'description' => 'Export content',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('contentexport_form'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Form builder : content_export select content type to export.
 */
function contentexport_form($form, &$form_state) {
  $node_types = node_type_get_types();
  $options = array();
  foreach ($node_types as $node_type) {
    $options[$node_type->type] = $node_type->name;
  }

  $form['content_type'] = array(
    '#title' => t('Select content type'),
    '#type' => 'select',
    '#options' => $options,
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Submit'),
  );

  return $form;
}

/**
 * Form submit handler : handle contentexport_form.
 */
function contentexport_form_submit($form, &$form_state) {
  $page_array = array();

  // Load nodes.
  $node_type = $form_state['values']['content_type'];
  $nodes = _contentexport_get_nodes($node_type);
//  dpm($nodes);
  // Cycle through all nodes to load any extra data, in this case it's taxonomy terms.
  // Note: loop values by reference so that it is possible to load the data into the same position of the array.
  foreach ($nodes as &$node) {
    // Cycle through each node property.
    foreach ($node as $property_name => &$property) {
      // Find the field properties.
      $fieldname_regex = '/^field_[a-z]*$/';
      if (preg_match($fieldname_regex, $property_name)) {
        // Load the field info for the field.
        $field_info = field_info_field($property_name);
//        dpm($field_info);
        // If the field is a taxonomy term reference, load the term.
        if ($field_info['type'] === 'taxonomy_term_reference') {
          if (isset($property['und']) && !empty($property['und'])) {
            foreach ($property['und'] as &$term) {
              $term = taxonomy_term_load($term['tid']);
            }
          }
        }
      }
    }
  }
//  dpm($nodes);
  // Export nodes.
  _export_nodes_json_unmanaged($nodes);

  return $page_array;
}

/**
 * Custom function : get all nodes of selected type.
 */
function _contentexport_get_nodes($node_type) {
  $query = db_select('node', 'n')
      ->fields('n', array('nid', 'type'))
      ->condition('type', $node_type);
  $nids = $query->execute()->fetchCol();

  $nodes = node_load_multiple($nids);

  return $nodes;
}

/**
 * Custom function : export given nodes to JSON format.
 */
function _export_nodes_json_unmanaged(array $nodes) {
  // Check if there is actual data to export.
  if (empty($nodes)) {
    // Inform user.
    drupal_set_message(t('Nothing to export.'), 'error');
//    drupal_goto('<front>');
    return;
  }

  // Build data array.
  $file_data = drupal_json_encode($nodes);
//  dpm($file_data);
  // Attempt export.
  try {
    $node_keys = array_keys($nodes);
    $first_node = $nodes[$node_keys[0]];

    // Create export directory.
    $directory = 'public://export/' . $first_node->type;
    if (!file_prepare_directory($directory, FILE_MODIFY_PERMISSIONS | FILE_CREATE_DIRECTORY)) {
      throw new Exception(t('Failed to create %directory.', array('%directory' => $directory)));
    }

    // Create JSON file.
    $filename = _export_generate_filename($first_node->type, 'json');
    $destination = $directory . '/' . $filename;
    $filename = file_unmanaged_save_data($file_data, $destination, FILE_EXISTS_REPLACE);
    if ($filename) {
      $url = file_create_url($filename);
      drupal_set_message(t('Saved file as %filename, accessible via !url.', array(
        '%filename' => $filename,
        '!url' => l(t('this URL'), $url),
      )));
    }
    else {
      throw new Exception(t('Failed to save the file.'));
    }

    // Create export image directory.
    $images_directory = 'public://export/' . $first_node->type . '/image';
    if (!file_prepare_directory($images_directory, FILE_MODIFY_PERMISSIONS | FILE_CREATE_DIRECTORY)) {
      throw new Exception(t('Failed to create %directory.', array('%directory' => $images_directory)));
    }

    // Copy node images.
    foreach ($nodes as $node) {
      foreach ($node->field_image['und'] as $image) {
        if (isset($image['uri']) && !empty($image['uri'])) {
          if (!file_unmanaged_copy($image['uri'], $images_directory, FILE_EXISTS_REPLACE)) {
            throw new Exception(t('Failed to copy %picture', array('%picture' => $image['uri'])));
          }
        }
      }
    }
    drupal_set_message(t('Node images copied to %directory', array('%directory' => $images_directory)));

    // Redirect to front.
    drupal_goto('<front>');
  }
  catch (Exception $exc) {
    // Display error message.
    drupal_set_message($exc->getMessage(), 'error');
    // Redirect to front.
    drupal_goto('<front>');
  }
}

/**
 * Custom function: Generate filename for export file.
 */
function _export_generate_filename($prefix, $extension) {
  $filename = $prefix;
  $filename .= '_' . format_date(time(), 'custom', 'd-m-Y');
  $filename .= '.' . $extension;

  return $filename;
}
